export const ActionTypes = {
	SET_DATA: 'SET_DATA',
	UPDATE_DATA: 'UPDATE_DATA',
	SET_SETTINGS_DATA: 'SET_SETTINGS_DATA',
	UPDATE_SETTINGS_DATA: 'UPDATE_SETTINGS_DATA',
	RESET_DATA: 'RESET_DATA',
	FETCH_DASHBOARD_DATA_REQUEST: 'FETCH_DASHBOARD_DATA_REQUEST',
	FETCH_DASHBOARD_DATA_SUCCESS: 'FETCH_DASHBOARD_DATA_SUCCESS',
	FETCH_DASHBOARD_DATA_FAILURE: 'FETCH_DASHBOARD_DATA_FAILURE',
	FETCH_FOLLOWUP_DATA_SUCCESS: 'FETCH_FOLLOWUP_DATA_SUCCESS',
	FETCH_PRODUCT_DATA_SUCCESS: 'FETCH_PRODUCT_DATA_SUCCESS',
	UPDATE_LICENSE_STATUS: 'UPDATE_LICENSE_STATUS',
};
